services:
  db:
    image: postgres:17
    container_name: link_reducer_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: link_reducer_backend
    env_file:
      - .env
    volumes:
      - ./backend/public:/var/www/html/public
      - ./backend/src:/var/www/html/src
      - ./backend/tests:/var/www/html/tests
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: link_reducer_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
