name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Création d'un .env temporaire pour Docker backend
      - name: Create .env
        run: |
          cat > .env << EOF
          DB_HOST=db
          DB_PORT=5432
          POSTGRES_DB=reducer
          POSTGRES_USER=reducer_user
          POSTGRES_PASSWORD=reducer_pass
          EOF
      
      - name: Start services
        run: docker compose up -d --wait
      
      - name: Run tests
        run: docker compose exec -T backend sh /var/www/html/tests/reduce_test.sh
      
      - name: Cleanup
        if: always()
        run: docker compose down -v

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watch=false
