name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Création d'un .env temporaire pour Docker backend
      - name: Create backend .env
        run: |
          echo "DB_HOST=db" >> backend/.env
          echo "DB_PORT=5432" >> backend/.env
          echo "POSTGRES_DB=reducer" >> backend/.env
          echo "POSTGRES_USER=reducer_user" >> backend/.env
          echo "POSTGRES_PASSWORD=reducer_pass" >> backend/.env
      
      - name: Move .env to project root
        run: mv backend/.env .env
        
      - name: Build backend
        run: docker compose build backend db

      - name: Start backend
        run: docker compose up -d backend db

      - name: Test backend
        run: docker compose run --rm backend sh /var/www/html/tests/reduce_test.sh

      - name: Stop backend containers
        run: docker compose down

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watch=false
